name: Main Workflow

on:
  schedule:
    - cron: '0 10 * * *'
      timezone: 'Asia/Hong_Kong'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/983387179513/locations/global/workloadIdentityPools/stock-fetcher-github-pool/providers/github-provider'
          service_account: 'st-fetcher@stock-fetcher-494612.iam.gserviceaccount.com'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.7'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
          GITHUB_ACTIONS: "true"
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          DRIVE_DIR_ID: ${{ secrets.DRIVE_DIR_ID }}
          CACHE_FILE_ID: ${{ secrets.CACHE_FILE_ID }}
          OUTPUT_FILE_ID: ${{ secrets.OUTPUT_FILE_ID }}
        run: python main.py
